# Generated by Django 3.1 on 2020-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Highest Bid'),
        ),
    ]
