# Generated by Django 3.1 on 2020-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
    ]
