# Generated by Django 3.1 on 2020-09-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='acitve',
            new_name='active',
        ),
    ]
