# Generated by Django 3.1 on 2020-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
