# Generated by Django 3.1 on 2020-09-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_offer_question_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='commentor',
            new_name='commenter',
        ),
    ]
